spring:
  datasource:
    password: 'root' #'coherent@123'
    url: 'jdbc:mysql://localhost:3306/unnamed' #'jdbc:mysql://95.217.209.135:3306/unnamed_dev?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC'
    username: 'root' #'remote'
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: "10000"
      maximum-pool-size: "20"
      minimum-idle: "5"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      naming: {physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl}
    properties:
      hibernate:
        format_sql: false
        enable_lazy_load_no_trans: true
      show-sql: true
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates